{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tuya",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatuur",
     "type": "timeseries",
     "gridPos": { "h": 18, "w": 17, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      { "expr": "tuya_device_wk_temp_current", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Huidige Temperatuur",
     "type": "table",
     "gridPos": { "h": 18, "w": 5, "x": 17, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      { "expr": "tuya_device_wk_temp_current" }
     ]
    },
    {
     "title": "Stopcontacten",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      { "expr": "tuya_device_cz_switch_1", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Windows Open",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "tuya_device_mcs_doorcontact_state",
       "legendFormat": "{{name}}"
      },
      { "expr": "tuya_device_mcs_switch", "legendFormat": "{{name}}" }
     ]
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Down or Not",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "rate(smokeping_requests_total[5m]) -\r\nrate(smokeping_response_duration_seconds_count[5m])",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "BTRFS",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 10, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (instance) (btrfs_device_write_io_errs)",
       "legendFormat": "write_io_errs {{instance}} "
      },
      {
       "expr": "sum by (instance) (btrfs_device_read_io_errs)",
       "legendFormat": "read_io_errs {{instance}} "
      },
      {
       "expr": "sum by (instance) (btrfs_device_corruption_errs)",
       "legendFormat": "corruption_errs {{instance}} "
      }
     ]
    },
    {
     "title": "Smart Healthy Status",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 12, "x": 10, "y": 1 },
     "targets": [
      { "expr": "smartmon_device_smart_healthy", "legendFormat": "{{instance}} {{disk}}" }
     ]
    }
   ]
  }
 ]
}