esphome:
  name: bluetooth-proxy-boven

esp32:
  variant: esp32c6
  board: esp32-c6-devkitm-1
  framework:
#    type: arduino
    type: esp-idf
    version: "5.4.0"
    platform_version: espressif32 @ 6.10.0

bluetooth_proxy:
  active: true

network:
  enable_ipv6: False

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 300s

ota:
  platform: esphome
  password: !secret wifi_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  use_address: "bluetooth-proxy-boven"
  domain: ".fritz.box"
  fast_connect: true

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 550ms
    active: true
  on_ble_advertise:
  - mac_address: "B0:E9:FE:53:B5:7D"  # floor0/bureau/switchbot
    then:
      - lambda: |-
          ESP_LOGD("ble_adv", "Found allowed device: floor0/bureau/switchbot");
  - mac_address: "B0:E9:FE:55:37:87"  # floor0/living/switchbot
    then:
      - lambda: |-
          ESP_LOGD("ble_adv", "Found allowed device: floor0/living/switchbot");
  - mac_address: "B0:E9:FE:55:35:C9"  # floor1/fen/switchbot
    then:
      - lambda: |-
          ESP_LOGD("ble_adv", "Found allowed device: floor1/fen/switchbot");
  - then:
    - lambda: |-
        ESP_LOGD("ble_adv", "Ignored device: %s", x.get_name().c_str());


sensor:
#  - platform: uptime
#    type: seconds
#    name: "floor1/bluetooth_proxy/uptime"
#    entity_category: diagnostic
  - platform: internal_temperature
    entity_category: diagnostic
    name: "floor1/bluetooth_proxy/internal_temperature"

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
