esphome:
  name: bluetooth-proxy-boven

esp32:
  variant: esp32c6
  board: esp32-c6-devkitm-1
  framework:
#    type: arduino
    type: esp-idf
    version: "5.4.0"
    platform_version: espressif32 @ 6.10.0
bluetooth_proxy:
  active: true

network:
  enable_ipv6: False

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 300s

ota:
  platform: esphome
  password: !secret wifi_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

esp32_ble_tracker:

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor
    entity_category: diagnostic
  - platform: internal_temperature
    entity_category: diagnostic
    name: "Internal Temperature"

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Berlin
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
