name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-22.11
      - uses: workflow/nix-shell-action@v3
        with:
          packages: 
          script: |
            nixos-rebuild --flake .#nhtpc build
            nix-shell --run "echo OK"